project_name: ns

builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    main: ./cmd/ns
    binary: ns
    flags:
      - -trimpath
    ldflags:
      - -s -w -X namespacelabs.dev/foundation/internal/cli/version.Tag=v{{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: macos
    env:
      - CGO_ENABLED=1
    main: ./cmd/ns
    binary: ns
    flags:
      - -trimpath
    ldflags:
      - -s -w -X namespacelabs.dev/foundation/internal/cli/version.Tag=v{{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

# signs:
#   - signature: "${artifact}_macos.dmg"
#     ids:
#       - macos
#     cmd: gon
#     args:
#       - cmd/ns/gon.hcl
#     artifacts: all

release:
  github:
    owner: namespacelabs
    name: foundation
  # extra_files:
  #   - glob: ./dist/fn_macos.dmg
  #   - glob: ./dist/fn_macos.zip

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^nochangelog"
      - "^Merge pull request"
      - "^Merge branch"

blobs:
  -
    # Publicly-accessible blobs (mainly to make installing easier while our repos are private).
    provider: s3
    region: us-east-2
    bucket: ns-releases
    folder: "{{ .ProjectName }}/v{{.Version}}"

brews:
  -
    tap:
      owner: namespacelabs
      name: homebrew-repo
    description: "Developer platform with a unified experience from development to production."
    homepage: "https://namespacelabs.com/"
    # Point to the publicly-accessible S3 builds instead of GitHub releases (which are in a private repo).
    url_template: "https://ns-releases.s3.us-east-2.amazonaws.com/{{.ProjectName}}/v{{.Version}}/{{.ArtifactName}}"
