# So the users don't need to fn login to get the "new version" message.
name: Publish fn version publicly

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - name: Get latest release
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1

      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_at }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"

      - name: Init new repo in dist folder and commit generated files
        run: |
          mkdir tmp
          cd tmp
          git init --initial-branch=gh-pages
          echo "{'tag_name': '${{ steps.last_release.outputs.tag_name }}', 'created_at': '${{ steps.last_release.outputs.created_at }}'}" > version.json
          cat version.json
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          repository: "namespacelabs/foundation-version"
          directory: ./tmp
